### ISSUE TITLE
gettext make doesn't complete?

### ISSUE THREAD

**Issue by BBaysinger** [kladd/pacman-osx#13]
Got to the 'make' command in step one, and it finished with this:

../libtool: line 1099: cd: .libs/libgettextlib.lax/libcroco_rpl.a: No such file or directory
make[5]: *** [libgettextlib.la] Error 1
make[4]: *** [all] Error 2
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

Not sure how to proceed from here.

**Comment by kladd** [comment]
I have not maintained this guide since Mavericks. The Yosemite guide is based on the developer preview at the time. So, thanks for taking the time to run through the steps.

That being said, I tried running the gettext compilation instructions against /tmp but could not reproduce your error above.

These were my steps (albeit on 10.12, not 10.10)

```
export CC=clang
./configure --prefix=/tmp # (this failed because I hadn't accepted the Xcode agreement)
sudo xcrun cc # (to accept the Xcode agreement)
./configure --prefix=/tmp # this worked now
make && make install
```

**Comment by BBaysinger** [comment]
That worked on my El Capitan 10.11.6. Thank you!

**Comment by kladd** [comment]
Closed for backlog bankruptcy reasons. Please reopen if this issue persists on recent macOS versions.
