### ISSUE TITLE
glibtoolize: command not found

### ISSUE THREAD

**Issue by BBaysinger** [kladd/pacman-osx#15]
When I run:

`PATH=$HOME/pacman-deps/bin:$PATH ./build/autogen.sh`

I get:

`./build/autogen.sh: line 56: glibtoolize: command not found`

Sorry to be a bugger today. Just not working either way, so kind of at a roadblock. Thanks for all your help.

**Comment by kladd** [comment]
It looks like I did not enable "Issues" on this repo, and didn't see the few issues opened here. Since this is from 2016 and the instructions have changed for more recent macOS/pacman versions, I'm going to close this one. If by chance you've tried the latest instructions and still have this issue please open again.
